"""WebSocket 보안(Origin 검증 · 토큰 인증 · 브루트포스 차단) 통합 테스트.

보안 수정(C-1/C-2/H-1)의 회귀를 막기 위한 테스트다. 실제 오디오 장치나 번역 모델을
열지 않도록 `pipeline` 을 모킹해 서버를 기동한다.
"""

from __future__ import annotations

import asyncio
import os

import pytest
from fastapi.testclient import TestClient

TOKEN = "test-token-abcdef123456"


@pytest.fixture
def client(monkeypatch):
    """오디오/모델을 열지 않는 테스트용 서버 클라이언트.

    - OPERATOR_TOKEN 을 고정해 토큰 인증 경로를 검증한다.
    - pipeline() 을 대체해 하드웨어(마이크)·외부 API 접근을 막는다.
    """
    monkeypatch.setenv("OPERATOR_TOKEN", TOKEN)
    monkeypatch.setenv("GEMINI_API_KEY", "test")
    monkeypatch.setenv("WS_HOST", "0.0.0.0")

    import ws_server

    async def fake_pipeline(settings):
        # 실제 파이프라인 대신 상태만 준비하고 대기 (오디오/모델 미접근)
        ws_server.state.settings = settings
        ws_server.state.loop = asyncio.get_running_loop()
        ws_server.state.languages = [{"code": "en", "color": "#ffffff"}]
        await asyncio.Event().wait()

    monkeypatch.setattr(ws_server, "pipeline", fake_pipeline)
    with TestClient(ws_server.app) as c:
        yield c


def _cmd(ws, cmd: dict) -> dict:
    """명령을 보내고 첫 응답을 받는다(init 은 이미 소비한 상태)."""
    ws.send_json(cmd)
    return ws.receive_json()


# ── C-1: Origin 검증 ────────────────────────────────────────────


def test_외부_origin_은_차단된다(client):
    """임의 외부 사이트가 WebSocket 으로 붙는 CSWSH 를 막는다."""
    with pytest.raises(Exception):  # 서버가 4403 으로 닫음
        with client.websocket_connect(
            "/ws", headers={"origin": "http://evil.example.com"}
        ) as ws:
            ws.receive_json()


def test_같은_호스트_origin_은_허용된다(client):
    """이 서버가 서빙하는 화면(같은 host)은 정상 동작해야 한다."""
    with client.websocket_connect(
        "/ws", headers={"origin": "http://testserver", "host": "testserver"}
    ) as ws:
        assert ws.receive_json()["type"] == "init"


def test_모바일_LAN_IP_접속은_허용된다(client):
    """폰이 http://<LAN IP>:8000/m 을 열었을 때와 같은 헤더 → 허용(회귀 방지)."""
    with client.websocket_connect(
        "/ws",
        headers={"origin": "http://192.168.1.190:8000", "host": "192.168.1.190:8000"},
    ) as ws:
        assert ws.receive_json()["type"] == "init"


def test_origin_없는_클라이언트는_허용된다(client):
    """OBS·curl 등 비브라우저는 CSWSH 대상이 아니므로 허용한다."""
    with client.websocket_connect("/ws") as ws:
        assert ws.receive_json()["type"] == "init"


def test_ALLOWED_ORIGINS_로_추가_허용할_수_있다(client, monkeypatch):
    monkeypatch.setenv("ALLOWED_ORIGINS", "https://sermon.example.org")
    with client.websocket_connect(
        "/ws", headers={"origin": "https://sermon.example.org"}
    ) as ws:
        assert ws.receive_json()["type"] == "init"


# ── C-2 / H-1: 토큰 인증 ────────────────────────────────────────


def test_토큰_없는_명령은_거부된다(client):
    """토큰이 설정돼 있으면 토큰 없는 운영 명령은 실행되지 않는다."""
    with client.websocket_connect("/ws") as ws:
        ws.receive_json()  # init
        assert _cmd(ws, {"cmd": "set_output", "enabled": False})["type"] == "auth_error"


def test_틀린_토큰은_거부된다(client):
    with client.websocket_connect("/ws") as ws:
        ws.receive_json()
        reply = _cmd(ws, {"cmd": "set_output", "enabled": False, "token": "wrong"})
        assert reply["type"] == "auth_error"


def test_정상_토큰이면_명령이_실행된다(client):
    """인증이 통과하면 기능은 그대로 동작해야 한다(기능 회귀 방지)."""
    with client.websocket_connect("/ws") as ws:
        ws.receive_json()
        reply = _cmd(ws, {"cmd": "set_output", "enabled": False, "token": TOKEN})
        assert reply["type"] == "output_state"
        assert reply["enabled"] is False


def test_인증_실패가_누적되면_연결이_끊긴다(client):
    """토큰 무차별 대입을 막는다(H-1)."""
    import ws_server

    with pytest.raises(Exception):
        with client.websocket_connect("/ws") as ws:
            ws.receive_json()
            # 허용 횟수를 넘겨 계속 시도하면 서버가 연결을 닫아야 한다
            for i in range(ws_server.MAX_AUTH_FAILURES + 2):
                ws.send_json({"cmd": "reset", "token": f"wrong-{i}"})
                ws.receive_json()


# ── 토큰 자동 생성(C-2) ─────────────────────────────────────────


def test_LAN_노출시_토큰이_자동_생성된다(monkeypatch):
    """토큰 미설정 + 0.0.0.0 이면 '인증 없음' 상태가 생기지 않아야 한다."""
    monkeypatch.delenv("OPERATOR_TOKEN", raising=False)
    monkeypatch.setenv("WS_HOST", "0.0.0.0")
    monkeypatch.setenv("GEMINI_API_KEY", "test")
    from config import Settings

    s = Settings.load()
    assert s.token_autogenerated is True
    assert len(s.operator_token) >= 16


def test_로컬_전용이면_토큰을_만들지_않는다(monkeypatch):
    """127.0.0.1 은 외부 노출이 없어 불필요한 마찰을 만들지 않는다."""
    monkeypatch.delenv("OPERATOR_TOKEN", raising=False)
    monkeypatch.setenv("WS_HOST", "127.0.0.1")
    monkeypatch.setenv("GEMINI_API_KEY", "test")
    from config import Settings

    s = Settings.load()
    assert s.token_autogenerated is False
    assert s.operator_token == ""
