"""FastAPI + WebSocket 자막 서버 (메인 엔트리포인트).

구성:
  - 오디오 캡처 → (언어별) Gemini Live Translate 세션 → 자막 안정화 → push
  - 목표 언어를 1~3개까지 동시에 운용 (언어마다 별도 세션, 같은 오디오를 fan-out)
  - 송출 화면(/)        : 언어 수만큼 행을 나눠 표시 (행별 글자색 지정)
  - 운영자 화면(/operator): 한/영 전사 + 송출 제어(언어/색/리셋/종료/스타일/소스)
  - WebSocket(/ws)      : 서버→클라이언트 자막/상태 push, 클라이언트→서버 명령 수신

운영자 명령(client → server):
  {"cmd": "reset"}                              화면 리셋
  {"cmd": "set_output", "enabled": bool}        송출 종료/재개
  {"cmd": "set_style", "style": {...}}          폰트/배경/안여백 변경
  {"cmd": "set_languages", "languages": [...]}  목표 언어 목록 [{code,color}]
  {"cmd": "set_device", "device": int|str}      오디오 입력 장치 전환
  {"cmd": "list_devices"}                       장치 목록 새로고침

실행:
    python server/ws_server.py
"""

from __future__ import annotations

import asyncio
import hmac
import json
import logging
import os
import socket
from contextlib import asynccontextmanager
from urllib.parse import urlparse

from fastapi import FastAPI, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, Response

from audio_input import (
    input_devices,
)
from config import Settings
from languages import LANGUAGES
from logging_setup import setup_logging

log = logging.getLogger("server")

# 설정 상수는 constants.py 로 분리(모듈 분리 2단계). 여기서 re-export 하여
# 기존 `from ws_server import <상수>` 호출부·테스트가 그대로 동작하게 한다.
from constants import (  # noqa: E402
    BACKEND_COOLDOWN_SEC,
    COMMAND_COOLDOWN_SEC,
    COST_PER_MIN,
    DEFAULT_COLORS,
    DEFAULT_STYLE,
    IDLE_STOP_MIN,
    IDLE_WARN_MIN,
    LABELS,
    LEVEL_PUSH_SEC,
    MAX_AUTH_FAILURES,
    MAX_LANGUAGES,
    MAX_QR_TEXT_CHARS,
    MAX_SCRIPT_CHARS,
    MAX_WS_CLIENTS,
    OPERATOR_URL_FILE,
    RUNTIME_DIR,
    SCRIPT_PATH,
    WEB_DIR,
    WS_MAX_MESSAGE_BYTES,
    _COOLDOWN_COMMANDS,
    _HEX_COLOR_RE,
)


# Hub 는 hub.py 로 분리(모듈 분리 2단계). re-export 로 기존 import 호환.
from hub import Hub, hub  # noqa: E402


# 상태·워커는 app_state.py 로 분리(모듈 분리 2단계). re-export 로 호환.
from app_state import AppState, LangWorker, state  # noqa: E402


# 입력 검증 순수 함수는 validation.py 로 분리(모듈 분리 2단계). re-export 로 호환.
from validation import (  # noqa: E402
    _is_hex_color,
    _sanitize_languages,
    _sanitize_style,
)


# 백엔드 전환·파이프라인·하트비트는 orchestration.py 로 분리(모듈 분리 2단계).
# re-export 로 lifespan·명령·테스트가 기존 이름 그대로 쓰게 한다.
from orchestration import (  # noqa: E402
    _build_backend,
    _is_too_quiet,
    _level_heartbeat,
    _log_pipeline_failure,
    _should_auto_stop,
    _usage_heartbeat,
    apply_languages,
    pipeline,
    set_broadcast,
    switch_backend,
)


@asynccontextmanager
async def lifespan(app: FastAPI):
    setup_logging()  # 어떤 실행 경로로 뜨든 로깅이 켜지도록 보장(중복 호출은 무시)
    settings = Settings.load()
    # 운영자 접속 URL(토큰 포함)을 로컬 파일로 남긴다 — start.sh 가 읽어 브라우저를 연다.
    # 토큰이 담기므로 소유자만 읽을 수 있게 권한을 제한하고 git 에서도 제외한다.
    try:
        RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
        url = f"http://localhost:{settings.ws_port}/operator"
        if settings.operator_token:
            url += f"?token={settings.operator_token}"
        OPERATOR_URL_FILE.write_text(url, encoding="utf-8")
        OPERATOR_URL_FILE.chmod(0o600)
    except Exception as exc:  # noqa: BLE001
        log.warning("운영자 URL 파일 기록 실패(무시): %s", exc)

    if settings.token_autogenerated:
        # 토큰이 없으면 자동 생성되므로 "인증 없음" 상태가 존재하지 않는다.
        # 운영자는 아래 URL 로 접속해야 조작할 수 있다.
        # 재사용/신규를 구분해 안내한다("재사용인데 매번 새로 만드는 듯" 오해 방지).
        head = (
            "저장된 운영자 토큰을 재사용합니다"
            if settings.token_reused
            else "운영자 토큰이 자동 생성되었습니다"
        )
        print(
            f"\n[server] 🔐 {head} (LAN 에 열려 있음).\n"
            f"          운영자 화면: http://localhost:{settings.ws_port}"
            f"/operator?token={settings.operator_token}\n"
            "          고정 토큰을 쓰려면 .env 에 OPERATOR_TOKEN 을 설정하세요.\n"
        )
    task = asyncio.create_task(pipeline(settings))
    task.add_done_callback(_log_pipeline_failure)
    log.info("파이프라인 시작 — 모델: %s", settings.model)
    try:
        yield
    finally:
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass


app = FastAPI(lifespan=lifespan)


@app.middleware("http")
async def _security_headers(request, call_next):  # noqa: ANN001, ANN201
    """기본 보안 헤더(L-1).

    - X-Frame-Options: 다른 사이트가 이 화면을 iframe 으로 감싸 오조작을 유도하는 것을 막음
    - X-Content-Type-Options: MIME 스니핑 방지
    - Referrer-Policy: 토큰이 담긴 URL 이 외부로 새어나가지 않도록 최소화
    """
    response = await call_next(request)
    response.headers.setdefault("X-Frame-Options", "SAMEORIGIN")
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("Referrer-Policy", "no-referrer")
    # 화면(HTML)은 캐시하지 않는다. 캐시되면 코드를 고쳐도 브라우저가 옛 화면을
    # 재사용해 "기능이 사라진 것처럼" 보인다(실제로 발생). QR/아이콘은 캐시 허용.
    if request.url.path in ("/", "/operator", "/m", "/qr-view"):
        response.headers["Cache-Control"] = "no-store, must-revalidate"
        # Starlette 의 MutableHeaders 는 pop() 이 없어 del 로 제거한다.
        for h in ("etag", "last-modified"):
            if h in response.headers:
                del response.headers[h]
    return response


@app.get("/")
async def overlay() -> FileResponse:
    return FileResponse(WEB_DIR / "subtitle-overlay" / "index.html")


@app.get("/operator")
async def operator() -> FileResponse:
    return FileResponse(WEB_DIR / "operator" / "index.html")


@app.get("/manifest.webmanifest")
async def manifest() -> dict:
    """송출 화면을 앱(PWA)으로 설치 가능하게 — 주소줄 없는 창으로 열림."""
    return {
        "name": "Sermon Subtitle",
        "short_name": "Subtitle",
        "start_url": "/",
        "scope": "/",
        "display": "standalone",   # 타이틀 바 O, 주소줄 X
        "background_color": "#000000",
        "theme_color": "#000000",
        "icons": [
            {"src": "/subtitle-overlay/icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "/subtitle-overlay/icon-512.png", "sizes": "512x512", "type": "image/png"},
        ],
    }


@app.get("/subtitle-overlay/{fname}")
async def overlay_asset(fname: str) -> FileResponse:
    """송출 화면 정적 자원(아이콘 등)."""
    path = (WEB_DIR / "subtitle-overlay" / fname).resolve()
    if path.parent != (WEB_DIR / "subtitle-overlay").resolve() or not path.exists():
        raise HTTPException(status_code=404)
    return FileResponse(path)


@app.get("/m")
async def mobile() -> FileResponse:
    """교인용 모바일 자막 — 폰에서 언어를 골라 그 언어만 본다(읽기 전용)."""
    return FileResponse(WEB_DIR / "mobile" / "index.html")


@app.get("/qr-view")
async def qr_view() -> FileResponse:
    """QR 코드를 크게 보여주는 별도 창(운영자가 팝업으로 연다)."""
    return FileResponse(WEB_DIR / "qr-view" / "index.html")


def _lan_ips() -> tuple[str, list[str]]:
    """이 컴퓨터의 LAN IPv4 를 검출. (primary, 후보 목록) 반환. 오프라인에서도 동작."""
    primary = "127.0.0.1"
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("8.8.8.8", 80))  # 패킷 전송 없이 기본 경로의 로컬 IP 만 확인
        primary = s.getsockname()[0]
    except Exception:  # noqa: BLE001
        pass
    finally:
        s.close()
    candidates = {primary}
    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            ip = info[4][0]
            if not ip.startswith("127."):
                candidates.add(ip)
    except Exception:  # noqa: BLE001
        pass
    ordered = [primary] + [c for c in sorted(candidates) if c != primary]
    return primary, ordered


@app.get("/lan-info")
async def lan_info() -> dict:
    """모바일 접속 주소(LAN IP) 안내 — 운영자 화면의 'QR' 기능이 사용."""
    primary, candidates = _lan_ips()
    port = state.settings.ws_port if state.settings else 8000
    return {
        "primary": primary,
        "port": port,
        "mobile_url": f"http://{primary}:{port}/m",
        "candidates": [
            {"ip": ip, "mobile_url": f"http://{ip}:{port}/m"} for ip in candidates
        ],
    }


@app.get("/qr.svg")
async def qr_svg(text: str) -> Response:
    """주어진 텍스트(URL)의 QR 코드를 SVG 로 생성해 반환 (로컬 생성, 인터넷 불필요).

    M-3: 길이 상한을 둔다. 상한이 없으면 임의 텍스트로 QR 을 대량 생성하게 만들어
    (오픈프록시처럼 악용) CPU 를 소모시킬 수 있다.
    """
    import io

    import segno

    if not text or len(text) > MAX_QR_TEXT_CHARS:
        raise HTTPException(
            status_code=400,
            detail=f"text 는 1~{MAX_QR_TEXT_CHARS}자여야 합니다.",
        )

    buf = io.BytesIO()
    segno.make(text, error="m").save(buf, kind="svg", scale=6, border=2, dark="#000", light="#fff")
    return Response(content=buf.getvalue(), media_type="image/svg+xml")


@app.get("/health")
async def health() -> dict:
    """모니터링용 상태 엔드포인트."""
    return {
        "status": "ok",
        "backend": state.backend.name if state.backend else None,
        "languages": [item["code"] for item in state.languages],
        "output_enabled": state.output_enabled,
        "audio_device": state.capture.current_device if state.capture else None,
        "clients": len(hub._clients),
    }


# 명령 처리는 commands.py 로 분리(모듈 분리 2단계). ws_endpoint 가 _handle_command 를 쓴다.
from commands import _handle_command  # noqa: E402


def _public_init() -> dict:
    """인증 없이 보내도 안전한 초기 상태(송출 화면·교인 폰이 쓰는 필드만).

    M-1: 예전에는 장치 목록·백엔드·용어 개수까지 모두 보냈는데, 이는 주소만 아는
    사람에게 내부 구성을 노출한다. 화면 동작에 필요한 값만 남긴다.
    """
    return {
        "type": "init",
        "style": state.style,
        "output_enabled": state.output_enabled,
        "layout": state.layout(),
        "languages": LANGUAGES,      # 선택 가능한 언어 목록(모바일에서 표시)
    }


def _operator_init() -> dict:
    """운영자 인증 후에만 보내는 내부 정보(장치명·백엔드·원고 등)."""
    return {
        "type": "operator_init",
        "broadcasting": state.broadcasting,
        "backend": state.backend.name if state.backend else "unknown",
        "default_colors": DEFAULT_COLORS,
        "max_languages": MAX_LANGUAGES,
        "devices": input_devices(),
        "current_device": state.capture.current_device if state.capture else None,
        "device_error": state.capture.error if state.capture else None,
        "gain": state.capture.gain if state.capture else 1.0,
        "script_terms": len(state.script.terms),
    }


def _origin_allowed(ws: WebSocket) -> bool:
    """WebSocket 핸드셰이크의 Origin 을 검증(CSWSH 방지).

    WebSocket 은 브라우저 동일출처정책 대상이 아니라서, 검사하지 않으면 임의의 외부
    웹페이지가 교회 LAN 의 이 서버에 붙어 명령을 보내거나 전사를 도청할 수 있다.

    이 앱의 화면(/, /operator, /m, /qr-view)은 모두 **이 서버가 서빙**하므로,
    Origin 의 host 가 요청이 들어온 host(=브라우저가 접속한 주소)와 같으면 허용한다.
    → 폰이 LAN IP 로 접속하는 모바일 자막도 그대로 동작한다.
    Origin 이 아예 없는 경우(curl, OBS 등 비브라우저)는 SOP 우회 위험이 없어 허용한다.
    허용 목록을 추가하려면 ALLOWED_ORIGINS(콤마 구분) 환경변수를 쓴다.
    """
    origin = ws.headers.get("origin")
    if not origin:
        return True  # 비브라우저 클라이언트(브라우저가 아니면 CSWSH 대상 아님)

    extra = {
        o.strip().rstrip("/")
        for o in os.getenv("ALLOWED_ORIGINS", "").split(",")
        if o.strip()
    }
    if origin.rstrip("/") in extra:
        return True

    try:
        origin_host = urlparse(origin).hostname
    except ValueError:
        return False
    if not origin_host:
        return False

    # 브라우저가 접속한 호스트(Host 헤더)와 같은 출처면 허용
    request_host = (ws.headers.get("host") or "").rsplit(":", 1)[0]
    if request_host and origin_host == request_host:
        return True
    # 로컬 접속은 항상 허용
    return origin_host in ("localhost", "127.0.0.1", "::1")


@app.websocket("/ws")
async def ws_endpoint(ws: WebSocket) -> None:
    if not _origin_allowed(ws):
        log.warning("⚠ 차단된 Origin 의 WebSocket 접속: %s", ws.headers.get("origin"))
        await ws.close(code=4403)
        return
    if hub.is_full:
        # 동시 연결 상한(H-4) — 자원 고갈 방지
        log.warning("⚠ 연결 상한(%d) 도달 — 새 접속 거부", MAX_WS_CLIENTS)
        await ws.close(code=4429)
        return
    await ws.accept()
    await hub.register(ws)
    auth_failures = 0
    operator_synced = False
    # 새 연결을 현재 상태로 동기화.
    # M-1: 인증 없는 연결(교인 폰·송출 화면)에는 **공용 필드만** 보낸다.
    #      장치명·백엔드·용어 개수 같은 내부 정보는 운영자 인증 후에 전달한다.
    await ws.send_text(json.dumps(_public_init(), ensure_ascii=False))
    try:
        while True:
            raw = await ws.receive_text()
            try:
                cmd = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if isinstance(cmd, dict) and "cmd" in cmd:
                token = state.settings.operator_token if state.settings else ""
                supplied = cmd.get("token")
                # 상수시간 비교(타이밍 공격 방지). 토큰이 있으면 항상 검사한다.
                ok = bool(token) and isinstance(supplied, str) and hmac.compare_digest(
                    supplied, token
                )
                # 인증이 확인되면(또는 토큰 미사용 환경이면) 운영자 정보를 1회 전달
                if (ok or not token) and not operator_synced:
                    operator_synced = True
                    hub.mark_operator(ws)
                    await ws.send_text(
                        json.dumps(_operator_init(), ensure_ascii=False)
                    )
                if token and not ok:
                    auth_failures += 1
                    await ws.send_text(
                        json.dumps(
                            {"type": "auth_error", "message": "운영자 토큰이 필요합니다."},
                            ensure_ascii=False,
                        )
                    )
                    # 브루트포스 차단: 실패가 누적되면 연결을 끊는다.
                    if auth_failures >= MAX_AUTH_FAILURES:
                        log.warning("⚠ 인증 실패 누적 — WebSocket 연결 종료")
                        await ws.close(code=4401)
                        break
                    await asyncio.sleep(0.5)  # 시도 속도 저하
                    continue
                await _handle_command(cmd)
    except WebSocketDisconnect:
        pass
    finally:
        await hub.unregister(ws)


# re-export: 다른 모듈·테스트가 `from ws_server import <이름>` 으로 쓰는 공개 심볼.
# 모듈 분리 후에도 기존 호출부·테스트가 그대로 동작하도록 유지한다(F401 방지).
__all__ = [
    "app",
    "Hub", "hub", "AppState", "LangWorker", "state",
    "_is_hex_color", "_sanitize_languages", "_sanitize_style",
    "_build_backend", "switch_backend", "set_broadcast", "apply_languages",
    "pipeline", "_usage_heartbeat", "_level_heartbeat", "_is_too_quiet",
    "_should_auto_stop", "_log_pipeline_failure", "_handle_command",
    "BACKEND_COOLDOWN_SEC", "COMMAND_COOLDOWN_SEC", "COST_PER_MIN",
    "DEFAULT_STYLE", "IDLE_STOP_MIN", "IDLE_WARN_MIN", "LABELS",
    "LEVEL_PUSH_SEC", "MAX_SCRIPT_CHARS", "MAX_WS_CLIENTS", "SCRIPT_PATH",
    "WS_MAX_MESSAGE_BYTES", "_COOLDOWN_COMMANDS", "_HEX_COLOR_RE",
]


if __name__ == "__main__":
    import uvicorn

    setup_logging()
    cfg = Settings.load()
    uvicorn.run(
        "ws_server:app",
        host=cfg.ws_host,
        port=cfg.ws_port,
        reload=False,
        # WebSocket 메시지 크기 상한(H-4) — 과대 메시지로 메모리 고갈 방지
        ws_max_size=WS_MAX_MESSAGE_BYTES,
    )
